site: notionallabs.github.io
url: www.jimhung.co.uk
title: TransTechnical Notional Labs
description: A Journal of Reverse Engineering, Security, and DFIR Research
twitter:
  username: notionallabs
  card: summary
  creator: notionallabs
author:
  twitter: notionallabs
  name: #yourusername
  avatar:
  email: jim@notional-labs.com
  url: www.notional-labs.com
permalink: pretty

baseurl: ""

#highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"